#! /bin/sh
# /etc/init.d/raspi_midi_instrument

### BEGIN INIT INFO
# Provides:          jackd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting MIDI instrument"
    # run application you want to start
    # Optimise the system for JACK
    /usr/local/bin/optimise_for_jack.sh
    # Run the instrument
    /home/pi/run_rhodes.sh
    ;;
  stop)
    echo "Stopping jackd"
    # kill application you want to stop
    killall jackd
    killall mod-host
    aconnect -x
    ;;
  *)
    echo "Usage: /etc/init.d/jackd-theo {start|stop}"
    exit 1
    ;;
esac

exit 0
